# Generated by Django 3.2.4 on 2021-06-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunek',
            },
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=25)),
                ('pochodzenie', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Reżyser',
                'verbose_name_plural': 'Reżyser',
            },
        ),
        migrations.CreateModel(
            name='Filmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('ocena', models.DecimalField(decimal_places=1, max_digits=1)),
                ('gatunek', models.ManyToManyField(to='Filmy.Gatunek')),
                ('rezyser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Filmy.rezyser')),
            ],
            options={
                'verbose_name': 'Filmy',
                'verbose_name_plural': 'Filmy',
            },
        ),
    ]
